### ISSUE TITLE
[Refactor]: EventBus관련 타입이 any인 문제

### ISSUE THREAD

**Issue by escape-engineering** [Challenge-Closure/Garlic-Toast#10]
### 불편 사항

https://github.com/Challenge-Closure/Garlic-Toast/blob/5f768f03d077f1fcefdf3c2630b07f7b8802488c/src/utils/eventBus.ts#L3-L7
해당부분의 topics와 listener의 타입이 불명확하게 지정되어있습니다.

### 개선 방안

#1 type/EventBus.ts에 타입을 지정해두고 관련 타입을 설정해 보았습니다.

**Comment by PJH-FE** [comment]
감사합니다
