### ISSUE TITLE
[Refactor]: App.tsx showToastButton()함수 리팩토링

### ISSUE THREAD

**Issue by Leekee0905** [Challenge-Closure/Garlic-Toast#6]
### 불편사항

showToastButton()함수에 if/else문이 주르륵 나열되어있는게 가독성이 떨어지는 것 같습니다.
또한 confirm 토스트의 res type이 any로 설정되어있습니다. 

### 개선 방안

#5 if/else문을 switch문으로 변경하고 res type을 확인해서 boolean으로 변경해보았습니다.

**Comment by PJH-FE** [comment]
감사합니다
