### ISSUE TITLE
[Bug]: Readme 에서 Contributing 로 이동시 404 페이지가 노출됩니다.

### ISSUE THREAD

**Issue by JaeSang1998** [Challenge-Closure/Garlic-Toast#7]
### 현상

Readme 에서 Contributing 로 이동시 404 페이지가 노출됩니다. .github 안에 있는 Contributing.md 파일로 잘 들어갈 수 있게 변경해주시면 좋을것 같습니다.

**Comment by PJH-FE** [comment]
#8 리드미 링크 수정 후 PR 등록했습니다.
